Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using MyFilms.Models;
using MyFilms.Services;

namespace MyFilms.Controllers
{
    public class SearchController : Controller
    {
        ApplicationContext db;

        public SearchController(ApplicationContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            var form = HttpContext.Request.Form;
            var searchString = form["searchString"];
            var result = KinopoiskAPIService.Search(searchString);
            result.Wait();
            ViewData["SearchString"] = searchString;
            ViewData["Result"] = result.Result;
            //ViewData["Authenticated"] = HttpContext.User.Identity.IsAuthenticated;
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFilms</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFilms.styles.css" asp-append-version="true" />
    <script type="text/javascript"
            src="//code.jquery.com/jquery-1.9.1.js">
    </script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">MyFilms</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Моя страница</a>
                            </li>
                        }
                    </ul>
                    <form asp-controller="Search" asp-action="Index" class="navbar-nav">
                        <input type="search" class="form-control" name="searchString"/>
                        <button type="submit" class="btn">Найти</button>
                    </form>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav pull-right">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@User.Identity.Name</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav pull-right">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Register">Регистрация</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Вход</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bd-footer text-muted py-4 px-4">
        <div class="container">
            &copy; 2023 - MyFilms
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>